name: Rust + Yew + WebAssembly CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Rust and WASM
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown
        override: true

    - name: Install tools
      run: |
        cargo install trunk wasm-bindgen-cli wasm-pack
        rustup component add clippy
        sudo apt-get update
        sudo apt-get install -y chromium-browser

    - name: Run unit & integration tests
      run: cargo test

    - name: Run clippy
      run: cargo clippy -- -D warnings

    - name: Run headless component tests (Chrome)
      run: wasm-pack test --headless --chrome

    - name: Build with trunk
      run: trunk build --release --public-url .